name: Weave
description: Web Developer from Somewhere
permalink: /:title/
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
- CNAME
